apiVersion: service.isf.ibm.com/v1
kind: FusionServiceInstance
metadata:
  name: odfmanager
  namespace: ibm-spectrum-fusion-ns
spec:
  creator: User
  doInstall: false
  parameters:
  - name: namespace
    provided: false
    value: openshift-storage
  - name: creator
    provided: false
    value: Fusion
  - name: backingStorageType
    provided: true
    value: Local
  - name: autoUpgrade
    provided: false
    value: "true"
  serviceDefinition: data-foundation-service
  triggerUpdate: false
